#Site settings
title: voidy
subtitle: stay foolish,stay hungry
email: mail@voidy.net
description: >
    voidy's blog,programing,python,jekyll.
keywords: "blog,python,linux,vim,reading"
markdown: redcarpet
highlighter: pygments
permalink: /:title

url: "http://voidy.net"
baseurl:

redcarpet:
  extensions: [strikethrough, tables]

sass:
  sass_dir: public/css
  style: :compressed

duoshuo_shortname: voidy

    #blog manager
ukagaka: true
highlighting-style: monokai
