# Site settings
title: voidy
subtitle: stay foolish,stay hungry
email: mail@voidy.net
description: >
    voidy's blog,programing,python,jekyll.
keywords: "blog,python,linux,vim,reading"
markdown: redcarpet
highlighter: pygment
permalink: /:title

url: "http://voidy.net"
baseurl:

redcarpet:
  extensions: [strikethrough, tables]

# Plugins
whitelist: []
gems:         ["jekyll-mentions", "jemoji", "jekyll-redirect-from"]

sass:
  sass_dir: public/css
  style: :compressed

# comments
duoshuo_shortname: voidy

# blog manager
ukagaka: true

# code theme    
highlighting-style: monokai
